I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1841, in script
    show kg waterbomb vigorous at left
Exception: Image 'kg waterbomb' does not accept attributes 'vigorous'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1841, in script
    show kg waterbomb vigorous at left
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\heon0\OneDrive\Desktop\renpy\renpy-8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'kg waterbomb' does not accept attributes 'vigorous'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
P1 Game Project 1.0
Wed Aug 21 12:21:36 2024
